name: nox-plugin-threat-model
version: 0.1.0
track: threat-modeling
description: STRIDE-based threat pattern detection in source code for automated threat modeling
tools:
  - name: scan
    description: Detect spoofing, tampering, repudiation, information disclosure, and elevation of privilege patterns
